name: werable_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.4.0
  flutter_profile_picture: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  provider: ^6.1.1
  syncfusion_flutter_gauges: ^29.2.8
  syncfusion_flutter_charts: 
  jwt_decoder: ^2.0.1
  intl:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
